### PR TITLE
PID tuning and repo fixes

### PR DESCRIPTION
**Pull request by brennan-macaig**
In this PR:

- Added PID and a basic autonomous mode to sprint for the baseline.
- Removed a bunch of "useless" files (.DS_Store, and others that can be safely ignored by all environments)
- Created a gitignore to stop these files from re-appearing
- Removed secondary copies of files denoted with a tilde (~) at the end of the file name.

### CODE REVIEW

**Comment by brennan-macaig** [comment]
The merge conflicts could be because I based off of the wrong version of the code (master not working-base). I'll double check these and see if that's the problem. If so I'll close the PR and re-create it on the proper codebase.

**Comment by brennan-macaig** [comment]
I fixed all the merge conflicts. Unless I changed something I assumed the server was the best version.

**Comment by brennan-macaig** [comment]
OK. More updates.

I've chased down all the bugs. Fixed everything. I removed a bunch of seemingly useless files, and added a command chooser to smartdashboard.

Hope everything works as expected. I'll flash all of this onto my raspberry pi (that I'm bringing for scouting reasons tomorrow).

I'll reach out to you folks tomorrow to see if we can do some auto tuning for those PID values on a practice field ASAP.

**EDIT: It's now safe to merge this in!**

**Review by SagesOfRPG — APPROVED** [review]
Thanks for your help!

**Pull request merged**
